baseURL = 'https://leonahxu/LeonaFilm.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = 'gallery'
copyright = "Â© Leona"

[params]
  defaultTheme = "dark"
  description = "film collections"
  title = "My Film"
  [params.author]
    email = "huixu368@gmail.com"
    name = "Hui Xu"
  [params.socialIcons]
    website = "https://leonahxu.github.io/LeonaFilm.github.io/"
    #instagram = ""
    #github = "https://github.com/nicokaiser/hugo-theme-gallery/"
